### ISSUE TITLE
BOM corrections 

### ISSUE THREAD

**Issue by povi2946** [bdring/Polar-Coaster#2]
Hi,
I understand that BOM is in progress and not everything is listed.
But I noticed that one listing is misleading.
In schematic and a digikey link C5,C6 capacitors are 47uF, but in the BOM it says it's 4.7uF. 
https://docs.google.com/spreadsheets/d/1ZX7-w3RRlV4LFHbHOMovw8RLWblGm1u_bLe6--jveR4/edit#gid=0&range=B34
Hopefully it's 47uF, as I already purchased some. 

Thanks
P.S. Once I finished building I would share a complete BOM for the update.

**Comment by bdring** [comment]
@povi2946 

Thanks, you are correct. I updated the BOM.
