### ISSUE TITLE
How to fasten the small gear?

### ISSUE THREAD

**Issue by dereulenspiegel** [bdring/Polar-Coaster#3]
Not really an issue, more of a question. What screw do I need to fasten the small gear? I tried with an M8x8mm screw. While that keeps the gear in place, the screw head interfers with the big gear. 
Thanks in advance :)

**Comment by bdring** [comment]
I think I used an m3 square nut with a 6mm set screw in that gear.

**Comment by dereulenspiegel** [comment]
Thanks, I will try that.
